### PR TITLE
Adding Swing Monkey

### PR DESCRIPTION
**Pull request by DuckMob**
Never done a Embedded Game before, but I believe I did everything correct. Cant test on LH cause of proxy.

### CODE REVIEW

**Comment by silvereengames** [comment]
You do have a pint. Evan, maybe merge to a branch to test then merge back to main?

**Comment by silvereengames** [comment]
Im not familiar on how embedded games testing work.

**Comment by DuckMob** [comment]
embedded games just proxies the link and shows it

**Comment by DuckMob** [comment]
but i cant see why it wouldnt work

**Comment by silvereengames** [comment]
Sometimes the site formatting is wrong.

**Comment by silvereengames** [comment]
I honestly thinks its good and if not we can restore the previous version.

**Comment by whos-evan** [comment]
It's completely fine, but it's better to serve assets locally.

**Pull request merged**
