### PR TITLE
n64 script

### PR DESCRIPTION
**Pull request by doggy7738**
game.html is the script to run it and you will have to put your directory or the file name
(idk witch one i use replit)

### CODE REVIEW

**Comment by Carter1190** [comment]
this wouldnt work as of commit [f1360ba](https://github.com/whos-evan/kazwire/pull/57/commits/f1360ba5ff5e5e175d37fa800f7015ac3a5900c7) due to the core being changed to mgba,but a n64 game being provided,please learn what youre doing before trying to pull request further.

**Comment by doggy7738** [comment]
i forgot to change that if you change it to n64 it will work

**Comment by Carter1190** [comment]
the fact you messed up with game.html 3 times makes me believe you dont know what youre doing,so i would suggest you learn how emulatorjs works first,then do this

**Comment by doggy7738** [comment]
it was a github issue

**Comment by whos-evan** [comment]
Many, many issues with this.
1. Did not append the games.json file
2. Did not add the game image to the /static/game/img folder
3. Did not have the proper naming structure for the game
4. Did not use the literal template provided in the /static/game/n64-template folder

In all this PR is extremely incomplete, please make every single change listed and DO not use external sources for libraries as they are extremely likely to be sinked by a schools DNS.

**Pull request closed without merging**
